<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Weasle-Tek Ltd_caret</name>
   <tag></tag>
   <elementGuidId>4fb7aa16-953f-4d61-9cff-4ec34f9477e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-toggle.organisation-name > span.caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navigation_hamburger']/ul[2]/li/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation_hamburger&quot;)/ul[@class=&quot;nav navbar-nav navbar-right hidden-xs&quot;]/li[@class=&quot;dropdown hidden-xs&quot;]/a[@class=&quot;dropdown-toggle organisation-name&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation_hamburger']/ul[2]/li/a/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
